//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resx.Home {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Index {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Guide.Web.Resources.Home.Index", typeof(Index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Articles.
        /// </summary>
        public static string AddNewArticles {
            get {
                return ResourceManager.GetString("AddNewArticles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download .
        /// </summary>
        public static string AdTextBody1 {
            get {
                return ResourceManager.GetString("AdTextBody1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  to your mobile device, locate and scan codes and the city will tell you way more than you can get from any regular guides. Old buildings, monuments, pieces of art, palaces, legendary backyards, churches, channels, squares and panoramas – all these have voice in CITYCODE. We are not limited by a standard tourist routine – we develop along with the city. No matter if you came from Rio de Janeiro, Russian province or were born in St.Petersburg – the city has enough secrets for everybody. For those in roaming  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string AdTextBody2 {
            get {
                return ResourceManager.GetString("AdTextBody2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CITYCODE is a new city project offering the unique story of St.Petersburg in the most comfortable way..
        /// </summary>
        public static string AdTextHeader {
            get {
                return ResourceManager.GetString("AdTextHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spb Guide.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found Out More.
        /// </summary>
        public static string FoundOutMore {
            get {
                return ResourceManager.GetString("FoundOutMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Involved.
        /// </summary>
        public static string GetInvolved {
            get {
                return ResourceManager.GetString("GetInvolved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan St. Petersburg!.
        /// </summary>
        public static string Slogan {
            get {
                return ResourceManager.GetString("Slogan", resourceCulture);
            }
        }
    }
}
